tokenizer_path: meta-llama/Llama-3.2-3B
model_path: meta-llama/Llama-3.2-3B
attn_classes_path: transformers.models.llama.modeling_llama.LLAMA_ATTENTION_CLASSES
train:
  teacher_model_path: meta-llama/Llama-3.2-3B
